# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3,5)

In [3]:
print("Matrix A:")
print(A)

print("\nNumber of dimensions (ndim):", A.ndim)
print("Shape:", A.shape)
print("Size (total number of elements):", A.size)
print("Data type (dtype):", A.dtype)

Matrix A:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Number of dimensions (ndim): 2
Shape: (3, 5)
Size (total number of elements): 15
Data type (dtype): int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [4]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [5]:

print("Matrix B:")
print(B)
print("\nMatrix C:")
print(C)

# Elementwise subtraction
subtraction = B - C
print("\nElementwise Subtraction (B - C):")
print(subtraction)

# Elementwise multiplication
elementwise_multiplication = B * C
print("\nElementwise Multiplication (B * C):")
print(elementwise_multiplication)

# Matrix multiplication using @ operator
matrix_multiplication = B @ C
print("\nMatrix Multiplication (B @ C):")
print(matrix_multiplication)

Matrix B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix C:
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]

Elementwise Subtraction (B - C):
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

Elementwise Multiplication (B * C):
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrix Multiplication (B @ C):
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [6]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
# Minimum value in the whole matrix
min_value = np.min(B)
print("\nMinimum value in the whole matrix:", min_value)

# Minimum value in each row
min_per_row = np.min(B, axis=1)
print("Minimum value in each row:", min_per_row)

# Minimum value in each column
min_per_col = np.min(B, axis=0)
print("Minimum value in each column:", min_per_col)

# Index of the minimum value in the whole matrix (flattened index)
min_index = np.argmin(B)
print("\nIndex of the minimum value in the whole matrix (flattened):", min_index)

# Index of the minimum value in each row
min_index_rowwise = np.argmin(B, axis=1)
print("Index of the minimum value in each row:", min_index_rowwise)

# Sum of all elements
total_sum = np.sum(B)
print("\nSum of all elements:", total_sum)

# Mean of each column
mean_per_col = np.mean(B, axis=0)
print("Mean for each column:", mean_per_col)

# Median of each column
median_per_col = np.median(B, axis=0)
print("Median for each column:", median_per_col)


Minimum value in the whole matrix: 1
Minimum value in each row: [1 4 7]
Minimum value in each column: [1 2 3]

Index of the minimum value in the whole matrix (flattened): 0
Index of the minimum value in each row: [0 0 0]

Sum of all elements: 45
Mean for each column: [4. 5. 6.]
Median for each column: [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [ ]:
print(A)

In [ ]:
A[1]

**Answer:**

In [9]:
print("\nA[1]:")
print(A[1])

# A is a 2D array with shape (3, 5) — 3 rows and 5 columns.
# A[1] gives you the second row (index 1) of the matrix.


A[1]:
[ 6  7  8  9 10]


### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [10]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [11]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [12]:
A = np.arange(1, 16).reshape(3, 5)

for element in np.nditer(A):
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [ ]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

In [ ]:
#b has 3 axes — it's a 3D array of shape (2, 3, 5).

# This means it's structured like:
# 2 blocks (axis 0),
# each block has 3 rows (axis 1),
# each row has 5 columns (axis 2).

Output (abridged for clarity):
[ 0  1  2  3  4  5 ... 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [ ]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [ ]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

In [ ]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [13]:
def add_mult_matrices(mat1, mat2, operation):
    # Validate input types
    if not isinstance(mat1, np.ndarray) or not isinstance(mat2, np.ndarray):
        raise TypeError("Both inputs must be numpy.ndarray.")
    
    # Validate operation argument
    if operation not in ['add', 'multiply']:
        raise ValueError("Operation must be either 'add' or 'multiply'.")
    
    if operation == 'add':
        # Check if shapes are the same
        if mat1.shape != mat2.shape:
            raise ValueError("For addition, matrices must have the same shape.")
        return mat1 + mat2
    
    elif operation == 'multiply':
        # Check if shapes are conformable for matrix multiplication
        if mat1.shape[1] != mat2.shape[0]:
            raise ValueError("For multiplication, the number of columns in the first matrix must equal the number of rows in the second.")
        return mat1 @ mat2
    
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix Addition
print(add_mult_matrices(A, B, 'add'))

# Matrix Multiplication
print(add_mult_matrices(A, B, 'multiply'))


[[ 6  8]
 [10 12]]
[[19 22]
 [43 50]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. Note, the function you created above can be used. 

In [14]:
## Uppgift 10.1.1
# Define vector x
x = np.array([4, 3])

# (a) Dimension of x
print("(a) Dimension of x:", x.shape)

# (b) 5x
print("(b) 5x =", 5 * x)

# (c) 3x
print("(c) 3x =", 3 * x)

# (d) 5x + 3x
print("(d) 5x + 3x =", 5 * x + 3 * x)

# (e) 8x
print("(e) 8x =", 8 * x)

# (f) 4x - x
print("(f) 4x - x =", 4 * x - x)

# (g) Transpose of x
x_T = x.reshape(2, 1).T  # or x[np.newaxis, :]
print("(g) x^T shape:", x_T.shape)

# (h) Is x + x^T defined?
try:
    result = x + x_T
    print("(h) x + x^T is defined. Result:\n", result)
except ValueError as e:
    print("(h) x + x^T is NOT defined:", e)

# (i) ||x|| (norm of x)
norm_x = np.linalg.norm(x)
print("(i) ||x|| =", norm_x)

## Uppgift 10.1.2
# Define vector v
v = np.array([3, 7, 0, 11])

# (a) Dimension of v
print("(a) Dimension of v:", v.shape)

# (b) 2v
print("(b) 2v =", 2 * v)

# Define vector v
v = np.array([3, 7, 0, 11])

# (c) 5v + 2v
print("(c) 5v + 2v =", 5 * v + 2 * v)

# (d) 4v - 2v
print("(d) 4v - 2v =", 4 * v - 2 * v)

# (e) Transpose of v
v_T = v.reshape(4, 1).T
print("(e) v^T shape:", v_T.shape)

# (f) Norm of v
norm_v = np.linalg.norm(v)
print("(f) ||v|| =", norm_v)

## Uppgift 10.1.3
# Define vectors v1 and v2
v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])

# (a) ||v1||
norm_v1 = np.linalg.norm(v1)
print("(a) ||v1|| =", norm_v1)

# (b) ||v1 - v2||
diff_norm = np.linalg.norm(v1 - v2)
print("(b) ||v1 - v2|| =", diff_norm)


(a) Dimension of x: (2,)
(b) 5x = [20 15]
(c) 3x = [12  9]
(d) 5x + 3x = [32 24]
(e) 8x = [32 24]
(f) 4x - x = [12  9]
(g) x^T shape: (1, 2)
(h) x + x^T is defined. Result:
 [[8 6]]
(i) ||x|| = 5.0
(a) Dimension of v: (4,)
(b) 2v = [ 6 14  0 22]
(c) 5v + 2v = [21 49  0 77]
(d) 4v - 2v = [ 6 14  0 22]
(e) v^T shape: (1, 4)
(f) ||v|| = 13.379088160259652
(a) ||v1|| = 7.14142842854285
(b) ||v1 - v2|| = 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. Note, the function you created above can be used.

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [ ]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

In [ ]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

In [ ]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

In [ ]:
# v1 is the original array, so v1.base is None.
# v2 is a view on v1, so v2.base points to v1.

# changing v2[-1] modifies the data in the buffer shared by both v1 and v2, so the last element of v1 is also modified when v2 is changed.
#v2 is a view on v1. This means v2 doesn't store its own data, but instead, it refers to the same underlying memory buffer as v1.
#  Thus, when you change an element in v2, it modifies the same data that v1 is pointing to. Since both arrays refer to the same memory, the change is reflected in both.