# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [3]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [5]:
A = np.arange(1, 16).reshape(3,5)

In [6]:
print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)

2
(3, 5)
15
int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [8]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [9]:
print(B - C)
print()
print(B * C)
print()
print(B @ C)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [11]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
print(np.min(B))
print(np.min(B, axis = 0))  # Taking the first column row-wise, then the second column and so on. 
print(np.min(B, axis = 1))  # Taking the first row column-wise, then the second row and so on.  
print() 

print(np.argmin(B))  # The output will be the index of the element in the form of a flattened array.
print(np.argmin(B, axis = 0))
print()

print(np.sum(B))
print(np.mean(B, axis = 1))
print(np.median(B, axis = 1))

1
[1 2 3]
[1 4 7]

0
[0 0 0]

45
[2. 5. 8.]
[2. 5. 8.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [14]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [15]:
A[1]

array([ 6,  7,  8,  9, 10])

When fewer indices are provided than the number of axes, the missing indices are considered complete slices.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [18]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [19]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [20]:
for i in A.ravel():  # Could use flatten() aswell. 
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

Two matrices stored where each has 3 rows and "suitable" number of columns.

In [23]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra (Vector and Matrix Algebra) calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [27]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

print(m1.shape)
print(m2.shape)



[[2 3]
 [4 5]]
(2, 2)
(2,)


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [29]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [30]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

print()

print(A+b)

[[1 2]
 [3 4]]
[2 2]

[[3 4]
 [5 6]]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [33]:
def add_mult_matrices(A, B, add_or_multiply):
    if not (isinstance(A, np.ndarray) and isinstance(B, np.ndarray)):
        raise Exception('Please provide two matrices.')
    
    if add_or_multiply == 'add':
        if not A.shape == B.shape:
            raise ValueError('Same shape required for matrix addition.')
        else: 
            return A + B
    elif add_or_multiply == 'multiply':
        if not A.shape[1] == B.shape[0]:
            raise ValueError('Columns and rows must be the shame length in matrix multiplicatio')
        else:
            return A @ B
    else:
        raise Exception('the add_or_multiply argument must be "add" or "multiply". ')

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. Note, the function you created above can be used. 

In [35]:
# 10.1.
x = np.array([4,3])
# a)
print(f'a) Dimension: 1 x {x.shape[0]}')
# b)
print(f'b) 5x = {5*x}')
# c)
print(f'c) 3x = {3*x}')
# d)
print(f"d) 5x + 3x = {add_mult_matrices(5*x, 3*x, 'add')}")
# e)
print(f'e) 8x = {8 * x}')
# f)
print(f"f) 4x - x = {add_mult_matrices(4*x, - x, 'add' )}")
# g)
y = x.reshape((2,1))
print(f'g) x^T =\n{y}')
print(f'g) New dimension: {y.shape[0]} x {y.shape[1]}')
# h)
# print(f"h) x + x^T = {add_mult_matrices(x, y, 'add')}")
# i) Solve it in a few ways here.
print(f'i) ||x|| = {np.linalg.norm(x)}')
print(f"i) ||x|| = {np.sqrt(add_mult_matrices(x.reshape(1,2),x.reshape(2,1),'multiply').flat[0])}")
print(f'i) ||x|| = {np.sqrt(np.sum(x**2))}')

a) Dimension: 1 x 2
b) 5x = [20 15]
c) 3x = [12  9]
d) 5x + 3x = [32 24]
e) 8x = [32 24]
f) 4x - x = [12  9]
g) x^T =
[[4]
 [3]]
g) New dimension: 2 x 1
i) ||x|| = 5.0
i) ||x|| = 5.0
i) ||x|| = 5.0


In [36]:
# 10.1.2
v=np.array([[3],[7],[0],[11]])
# a)
print(f'a) Dimension: {v.shape[0]} x {v.shape[1]}')
# b)
print(f'b) 2v =\n{2*v}')
# c)
print(f"c) 5v + 2v =\n{add_mult_matrices(5*v,2*v,'add')}")
# d)
print(f"d) 4v - 2v =\n{add_mult_matrices(4*v,-2*v,'add')}")
# e)
print(f'e) v^T = {v.T.reshape(-1)}')
print(f'Dimension: {v.T.shape[0]} x {v.T.shape[1]}')
# f) Solve it in a few ways here
print(f'f) ||v|| = {np.linalg.norm(v)}')
print(f"f) ||v|| = {np.sqrt(add_mult_matrices(v.reshape(1,4),v,'multiply').flat[0])}")
print(f'f) ||v| = {np.sqrt(np.sum(v**2))}')

a) Dimension: 4 x 1
b) 2v =
[[ 6]
 [14]
 [ 0]
 [22]]
c) 5v + 2v =
[[21]
 [49]
 [ 0]
 [77]]
d) 4v - 2v =
[[ 6]
 [14]
 [ 0]
 [22]]
e) v^T = [ 3  7  0 11]
Dimension: 1 x 4
f) ||v|| = 13.379088160259652
f) ||v|| = 13.379088160259652
f) ||v| = 13.379088160259652


In [37]:
# 10.1.3
v1=np.array([4,3,1,5])
v2=np.array([2,3,1,1])

#a)
print(f'a) ||v1|| = {np.linalg.norm(v1)}')
print(f"a) ||v1|| = {np.sqrt(add_mult_matrices(v1.reshape(1,4),v1.reshape(4,1),'multiply').flat[0])}")
print(f'a) ||v1|| = {np.sqrt(np.sum(v1**2))}')
# b)
print(f'b) ||v1 - v2|| = {np.linalg.norm(v1 - v2)}')
print(f"b) ||v1 - v2|| = {np.sqrt(add_mult_matrices((v1-v2).reshape(1,4),(v1-v2).reshape(4,1),'multiply').flat[0])}")
print(f'b) ||v1 - v2|| = {np.sqrt(np.sum((v1-v2)**2))}')

a) ||v1|| = 7.14142842854285
a) ||v1|| = 7.14142842854285
a) ||v1|| = 7.14142842854285
b) ||v1 - v2|| = 4.47213595499958
b) ||v1 - v2|| = 4.47213595499958
b) ||v1 - v2|| = 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. Note, the function you created above can be used. 

In [39]:
# 10.2.1
A=np.array([[2,1,-1],[1,-1,1]])
B=np.array([[4,-2,1],[2,-4,-2]])
C=np.array([[1,2],[2,1]])
D=np.array([[3,4],[4,3]])
E=np.array([[1],[2]])
I=np.array([[1,0],[0,1]])

# a)
print(f'a) 2A =\n{2*A}\n')
# b)
print(f"b) B-2A =\n{add_mult_matrices(B, -2*A, 'add')}\n")
# c)
# print(f"c) 3C-2E =\n{add_mult_matrices(3*C, -2*E, 'add')}\n")
# d)
print(f"d) 2D - 3C =\n{add_mult_matrices(2*D, -3*C, 'add')}\n")
# e)
print(f"e) D^T+2D =\n{add_mult_matrices(D.T, 2*D, 'add')}\n")
# f)
print(f"f) 2C^T - 2D^T =\n{add_mult_matrices(2*C.T,-2*D.T,'add')}\n")
# g)
# print(f"g) A^T - B =\n{add_mult_matrices(A.T, -B, 'add')}\n")
# h)
# print(f"h) AC = \n{add_mult_matrices(A,C,'multiply')}\n")
# i)
print(f"i) CD =\n{add_mult_matrices(C,D,'multiply')}\n")
# j)
print(f"j) CB =\n{add_mult_matrices(C,B,'multiply')}\n")
# k)
print(f"k) CI =\n{add_mult_matrices(C,I,'multiply')}\n")
# l)
print(f"l) AB^T =\n{add_mult_matrices(A,B.T,'multiply')}")

a) 2A =
[[ 4  2 -2]
 [ 2 -2  2]]

b) B-2A =
[[ 0 -4  3]
 [ 0 -2 -4]]

d) 2D - 3C =
[[3 2]
 [2 3]]

e) D^T+2D =
[[ 9 12]
 [12  9]]

f) 2C^T - 2D^T =
[[-4 -4]
 [-4 -4]]

i) CD =
[[11 10]
 [10 11]]

j) CB =
[[  8 -10  -3]
 [ 10  -8   0]]

k) CI =
[[1 2]
 [2 1]]

l) AB^T =
[[5 2]
 [7 4]]


In [40]:
# 10.2.2
A=np.array([[2,3,4],[5,4,1]])
print(f"AA^T =\n{add_mult_matrices(A,A.T,'multiply')}")

AA^T =
[[29 26]
 [26 42]]


In [41]:
# 10.2.3 

A, B, C=np.array([[1,2],[2,4]]), np.array([[2,1],[1,3]]), np.array([[4,3],[0,2]])
print(f"AB = AC: {bool(np.prod(add_mult_matrices(A,B,'multiply').__eq__(add_mult_matrices(A,C,'multiply'))))}")
print(f"B = C: {bool(np.prod(B.__eq__(C)))}")

AB = AC: True
B = C: False


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [44]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [45]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [46]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
